name: 7.4

on:
  push:
    paths:
      - ".github/workflows/image_7_4.yml"
      - "7.4/**"
      - "overlay/**"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read PHP major version
        uses: bencgreen/read-file-action@v1
        with:
          path: ./7.4/PHP_MAJOR
        id: php_major
      -
        name: Read PHP minor version
        uses: bencgreen/read-file-action@v1
        with:
          path: ./7.4/PHP_MINOR
        id: php_minor
      -
        name: Read PHP revision version
        uses: bencgreen/read-file-action@v1
        with:
          path: ./7.4/PHP_REVISION
        id: php_revision
      -
        name: Read version
        uses: bencgreen/read-file-action@v1
        with:
          path: ./7.4/VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./7.4/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          #platforms: linux/amd64,linux/arm/v7
          #platforms: linux/amd64,linux/arm64
          tags: |
            bcgdesign/wordpress:latest
            bcgdesign/wordpress:php-${{ steps.php_major.outputs.content }}
            bcgdesign/wordpress:php-${{ steps.php_minor.outputs.content }}
            bcgdesign/wordpress:php-${{ steps.php_revision.outputs.content }}
            bcgdesign/wordpress:php-${{ steps.version.outputs.content }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
